title:              Angus Doherty
email:              angusdoh@gmail.com
description:        Data Scientist
author:             Angus Doherty
baseurl:            "/"
url:                "https://anqus.github.io"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: angusdoherty

# Social Profiles
twitter_username:   
github_username:    anqus
facebook_username:  
instagram_username: anqus
linkedin_username:  angusdoherty

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-88LCN289W8 # put your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
