title:              Angus Doherty
email:              angusdoh@gmail.com
description:        Data Scientist
author:             Angus Doherty
baseurl:            "/"
url:                "https://anqus.github.io"

# Social Profiles
twitter_username:   
github_username:    anqus
facebook_username:  
instagram_username: anqus
linkedin_username:  angusdoherty

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
